# Generated by Django 4.1.1 on 2022-11-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='realtor_email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
